// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventlib/messages/device_info.proto

package com.akhiltest.analytics.proto.model.messages;

public final class DeviceInfoMsg {
  private DeviceInfoMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eventlib.messages.DeviceInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    java.lang.String getDeviceId();
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>string asset = 2;</code>
     * @return The asset.
     */
    java.lang.String getAsset();
    /**
     * <code>string asset = 2;</code>
     * @return The bytes for asset.
     */
    com.google.protobuf.ByteString
        getAssetBytes();

    /**
     * <code>string category = 3;</code>
     * @return The category.
     */
    java.lang.String getCategory();
    /**
     * <code>string category = 3;</code>
     * @return The bytes for category.
     */
    com.google.protobuf.ByteString
        getCategoryBytes();

    /**
     * <code>string control = 4;</code>
     * @return The control.
     */
    java.lang.String getControl();
    /**
     * <code>string control = 4;</code>
     * @return The bytes for control.
     */
    com.google.protobuf.ByteString
        getControlBytes();

    /**
     * <code>repeated string function = 5;</code>
     * @return A list containing the function.
     */
    java.util.List<java.lang.String>
        getFunctionList();
    /**
     * <code>repeated string function = 5;</code>
     * @return The count of function.
     */
    int getFunctionCount();
    /**
     * <code>repeated string function = 5;</code>
     * @param index The index of the element to return.
     * @return The function at the given index.
     */
    java.lang.String getFunction(int index);
    /**
     * <code>repeated string function = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the function at the given index.
     */
    com.google.protobuf.ByteString
        getFunctionBytes(int index);

    /**
     * <code>string os = 6;</code>
     * @return The os.
     */
    java.lang.String getOs();
    /**
     * <code>string os = 6;</code>
     * @return The bytes for os.
     */
    com.google.protobuf.ByteString
        getOsBytes();

    /**
     * <code>string os_version = 7;</code>
     * @return The osVersion.
     */
    java.lang.String getOsVersion();
    /**
     * <code>string os_version = 7;</code>
     * @return The bytes for osVersion.
     */
    com.google.protobuf.ByteString
        getOsVersionBytes();

    /**
     * <code>string ownership = 8;</code>
     * @return The ownership.
     */
    java.lang.String getOwnership();
    /**
     * <code>string ownership = 8;</code>
     * @return The bytes for ownership.
     */
    com.google.protobuf.ByteString
        getOwnershipBytes();

    /**
     * <code>string type = 9;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <code>string type = 9;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string mfg = 10;</code>
     * @return The mfg.
     */
    java.lang.String getMfg();
    /**
     * <code>string mfg = 10;</code>
     * @return The bytes for mfg.
     */
    com.google.protobuf.ByteString
        getMfgBytes();

    /**
     * <code>repeated string username = 11;</code>
     * @return A list containing the username.
     */
    java.util.List<java.lang.String>
        getUsernameList();
    /**
     * <code>repeated string username = 11;</code>
     * @return The count of username.
     */
    int getUsernameCount();
    /**
     * <code>repeated string username = 11;</code>
     * @param index The index of the element to return.
     * @return The username at the given index.
     */
    java.lang.String getUsername(int index);
    /**
     * <code>repeated string username = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the username at the given index.
     */
    com.google.protobuf.ByteString
        getUsernameBytes(int index);

    /**
     * <code>float total_risk = 12;</code>
     * @return The totalRisk.
     */
    float getTotalRisk();

    /**
     * <code>.google.protobuf.Timestamp firstseen = 13;</code>
     * @return Whether the firstseen field is set.
     */
    boolean hasFirstseen();
    /**
     * <code>.google.protobuf.Timestamp firstseen = 13;</code>
     * @return The firstseen.
     */
    com.google.protobuf.Timestamp getFirstseen();
    /**
     * <code>.google.protobuf.Timestamp firstseen = 13;</code>
     */
    com.google.protobuf.TimestampOrBuilder getFirstseenOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp lastseen = 14;</code>
     * @return Whether the lastseen field is set.
     */
    boolean hasLastseen();
    /**
     * <code>.google.protobuf.Timestamp lastseen = 14;</code>
     * @return The lastseen.
     */
    com.google.protobuf.Timestamp getLastseen();
    /**
     * <code>.google.protobuf.Timestamp lastseen = 14;</code>
     */
    com.google.protobuf.TimestampOrBuilder getLastseenOrBuilder();
  }
  /**
   * Protobuf type {@code eventlib.messages.DeviceInfo}
   */
  public static final class DeviceInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:eventlib.messages.DeviceInfo)
      DeviceInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceInfo.newBuilder() to construct.
    private DeviceInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceInfo() {
      deviceId_ = "";
      asset_ = "";
      category_ = "";
      control_ = "";
      function_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      os_ = "";
      osVersion_ = "";
      ownership_ = "";
      type_ = "";
      mfg_ = "";
      username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeviceInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              asset_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              category_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              control_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                function_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              function_.add(s);
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              os_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              osVersion_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              ownership_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              mfg_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                username_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              username_.add(s);
              break;
            }
            case 101: {

              totalRisk_ = input.readFloat();
              break;
            }
            case 106: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (firstseen_ != null) {
                subBuilder = firstseen_.toBuilder();
              }
              firstseen_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(firstseen_);
                firstseen_ = subBuilder.buildPartial();
              }

              break;
            }
            case 114: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (lastseen_ != null) {
                subBuilder = lastseen_.toBuilder();
              }
              lastseen_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(lastseen_);
                lastseen_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          function_ = function_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          username_ = username_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.internal_static_eventlib_messages_DeviceInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.internal_static_eventlib_messages_DeviceInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo.class, com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo.Builder.class);
    }

    public static final int DEVICE_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object deviceId_;
    /**
     * <code>string device_id = 1;</code>
     * @return The deviceId.
     */
    @java.lang.Override
    public java.lang.String getDeviceId() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string device_id = 1;</code>
     * @return The bytes for deviceId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      java.lang.Object ref = deviceId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ASSET_FIELD_NUMBER = 2;
    private volatile java.lang.Object asset_;
    /**
     * <code>string asset = 2;</code>
     * @return The asset.
     */
    @java.lang.Override
    public java.lang.String getAsset() {
      java.lang.Object ref = asset_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asset_ = s;
        return s;
      }
    }
    /**
     * <code>string asset = 2;</code>
     * @return The bytes for asset.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAssetBytes() {
      java.lang.Object ref = asset_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asset_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CATEGORY_FIELD_NUMBER = 3;
    private volatile java.lang.Object category_;
    /**
     * <code>string category = 3;</code>
     * @return The category.
     */
    @java.lang.Override
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      }
    }
    /**
     * <code>string category = 3;</code>
     * @return The bytes for category.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTROL_FIELD_NUMBER = 4;
    private volatile java.lang.Object control_;
    /**
     * <code>string control = 4;</code>
     * @return The control.
     */
    @java.lang.Override
    public java.lang.String getControl() {
      java.lang.Object ref = control_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        control_ = s;
        return s;
      }
    }
    /**
     * <code>string control = 4;</code>
     * @return The bytes for control.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getControlBytes() {
      java.lang.Object ref = control_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        control_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCTION_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList function_;
    /**
     * <code>repeated string function = 5;</code>
     * @return A list containing the function.
     */
    public com.google.protobuf.ProtocolStringList
        getFunctionList() {
      return function_;
    }
    /**
     * <code>repeated string function = 5;</code>
     * @return The count of function.
     */
    public int getFunctionCount() {
      return function_.size();
    }
    /**
     * <code>repeated string function = 5;</code>
     * @param index The index of the element to return.
     * @return The function at the given index.
     */
    public java.lang.String getFunction(int index) {
      return function_.get(index);
    }
    /**
     * <code>repeated string function = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the function at the given index.
     */
    public com.google.protobuf.ByteString
        getFunctionBytes(int index) {
      return function_.getByteString(index);
    }

    public static final int OS_FIELD_NUMBER = 6;
    private volatile java.lang.Object os_;
    /**
     * <code>string os = 6;</code>
     * @return The os.
     */
    @java.lang.Override
    public java.lang.String getOs() {
      java.lang.Object ref = os_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        os_ = s;
        return s;
      }
    }
    /**
     * <code>string os = 6;</code>
     * @return The bytes for os.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOsBytes() {
      java.lang.Object ref = os_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        os_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OS_VERSION_FIELD_NUMBER = 7;
    private volatile java.lang.Object osVersion_;
    /**
     * <code>string os_version = 7;</code>
     * @return The osVersion.
     */
    @java.lang.Override
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string os_version = 7;</code>
     * @return The bytes for osVersion.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OWNERSHIP_FIELD_NUMBER = 8;
    private volatile java.lang.Object ownership_;
    /**
     * <code>string ownership = 8;</code>
     * @return The ownership.
     */
    @java.lang.Override
    public java.lang.String getOwnership() {
      java.lang.Object ref = ownership_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownership_ = s;
        return s;
      }
    }
    /**
     * <code>string ownership = 8;</code>
     * @return The bytes for ownership.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getOwnershipBytes() {
      java.lang.Object ref = ownership_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownership_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 9;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 9;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 9;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MFG_FIELD_NUMBER = 10;
    private volatile java.lang.Object mfg_;
    /**
     * <code>string mfg = 10;</code>
     * @return The mfg.
     */
    @java.lang.Override
    public java.lang.String getMfg() {
      java.lang.Object ref = mfg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mfg_ = s;
        return s;
      }
    }
    /**
     * <code>string mfg = 10;</code>
     * @return The bytes for mfg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMfgBytes() {
      java.lang.Object ref = mfg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mfg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 11;
    private com.google.protobuf.LazyStringList username_;
    /**
     * <code>repeated string username = 11;</code>
     * @return A list containing the username.
     */
    public com.google.protobuf.ProtocolStringList
        getUsernameList() {
      return username_;
    }
    /**
     * <code>repeated string username = 11;</code>
     * @return The count of username.
     */
    public int getUsernameCount() {
      return username_.size();
    }
    /**
     * <code>repeated string username = 11;</code>
     * @param index The index of the element to return.
     * @return The username at the given index.
     */
    public java.lang.String getUsername(int index) {
      return username_.get(index);
    }
    /**
     * <code>repeated string username = 11;</code>
     * @param index The index of the value to return.
     * @return The bytes of the username at the given index.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes(int index) {
      return username_.getByteString(index);
    }

    public static final int TOTAL_RISK_FIELD_NUMBER = 12;
    private float totalRisk_;
    /**
     * <code>float total_risk = 12;</code>
     * @return The totalRisk.
     */
    @java.lang.Override
    public float getTotalRisk() {
      return totalRisk_;
    }

    public static final int FIRSTSEEN_FIELD_NUMBER = 13;
    private com.google.protobuf.Timestamp firstseen_;
    /**
     * <code>.google.protobuf.Timestamp firstseen = 13;</code>
     * @return Whether the firstseen field is set.
     */
    @java.lang.Override
    public boolean hasFirstseen() {
      return firstseen_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp firstseen = 13;</code>
     * @return The firstseen.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getFirstseen() {
      return firstseen_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstseen_;
    }
    /**
     * <code>.google.protobuf.Timestamp firstseen = 13;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getFirstseenOrBuilder() {
      return getFirstseen();
    }

    public static final int LASTSEEN_FIELD_NUMBER = 14;
    private com.google.protobuf.Timestamp lastseen_;
    /**
     * <code>.google.protobuf.Timestamp lastseen = 14;</code>
     * @return Whether the lastseen field is set.
     */
    @java.lang.Override
    public boolean hasLastseen() {
      return lastseen_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp lastseen = 14;</code>
     * @return The lastseen.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getLastseen() {
      return lastseen_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastseen_;
    }
    /**
     * <code>.google.protobuf.Timestamp lastseen = 14;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getLastseenOrBuilder() {
      return getLastseen();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getAssetBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, asset_);
      }
      if (!getCategoryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, category_);
      }
      if (!getControlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, control_);
      }
      for (int i = 0; i < function_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, function_.getRaw(i));
      }
      if (!getOsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, os_);
      }
      if (!getOsVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, osVersion_);
      }
      if (!getOwnershipBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, ownership_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, type_);
      }
      if (!getMfgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, mfg_);
      }
      for (int i = 0; i < username_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, username_.getRaw(i));
      }
      if (totalRisk_ != 0F) {
        output.writeFloat(12, totalRisk_);
      }
      if (firstseen_ != null) {
        output.writeMessage(13, getFirstseen());
      }
      if (lastseen_ != null) {
        output.writeMessage(14, getLastseen());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getAssetBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, asset_);
      }
      if (!getCategoryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, category_);
      }
      if (!getControlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, control_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < function_.size(); i++) {
          dataSize += computeStringSizeNoTag(function_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getFunctionList().size();
      }
      if (!getOsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, os_);
      }
      if (!getOsVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, osVersion_);
      }
      if (!getOwnershipBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, ownership_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, type_);
      }
      if (!getMfgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, mfg_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < username_.size(); i++) {
          dataSize += computeStringSizeNoTag(username_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getUsernameList().size();
      }
      if (totalRisk_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, totalRisk_);
      }
      if (firstseen_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getFirstseen());
      }
      if (lastseen_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getLastseen());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo)) {
        return super.equals(obj);
      }
      com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo other = (com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo) obj;

      if (!getDeviceId()
          .equals(other.getDeviceId())) return false;
      if (!getAsset()
          .equals(other.getAsset())) return false;
      if (!getCategory()
          .equals(other.getCategory())) return false;
      if (!getControl()
          .equals(other.getControl())) return false;
      if (!getFunctionList()
          .equals(other.getFunctionList())) return false;
      if (!getOs()
          .equals(other.getOs())) return false;
      if (!getOsVersion()
          .equals(other.getOsVersion())) return false;
      if (!getOwnership()
          .equals(other.getOwnership())) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getMfg()
          .equals(other.getMfg())) return false;
      if (!getUsernameList()
          .equals(other.getUsernameList())) return false;
      if (java.lang.Float.floatToIntBits(getTotalRisk())
          != java.lang.Float.floatToIntBits(
              other.getTotalRisk())) return false;
      if (hasFirstseen() != other.hasFirstseen()) return false;
      if (hasFirstseen()) {
        if (!getFirstseen()
            .equals(other.getFirstseen())) return false;
      }
      if (hasLastseen() != other.hasLastseen()) return false;
      if (hasLastseen()) {
        if (!getLastseen()
            .equals(other.getLastseen())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + ASSET_FIELD_NUMBER;
      hash = (53 * hash) + getAsset().hashCode();
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
      hash = (37 * hash) + CONTROL_FIELD_NUMBER;
      hash = (53 * hash) + getControl().hashCode();
      if (getFunctionCount() > 0) {
        hash = (37 * hash) + FUNCTION_FIELD_NUMBER;
        hash = (53 * hash) + getFunctionList().hashCode();
      }
      hash = (37 * hash) + OS_FIELD_NUMBER;
      hash = (53 * hash) + getOs().hashCode();
      hash = (37 * hash) + OS_VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getOsVersion().hashCode();
      hash = (37 * hash) + OWNERSHIP_FIELD_NUMBER;
      hash = (53 * hash) + getOwnership().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + MFG_FIELD_NUMBER;
      hash = (53 * hash) + getMfg().hashCode();
      if (getUsernameCount() > 0) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsernameList().hashCode();
      }
      hash = (37 * hash) + TOTAL_RISK_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTotalRisk());
      if (hasFirstseen()) {
        hash = (37 * hash) + FIRSTSEEN_FIELD_NUMBER;
        hash = (53 * hash) + getFirstseen().hashCode();
      }
      if (hasLastseen()) {
        hash = (37 * hash) + LASTSEEN_FIELD_NUMBER;
        hash = (53 * hash) + getLastseen().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eventlib.messages.DeviceInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eventlib.messages.DeviceInfo)
        com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.internal_static_eventlib_messages_DeviceInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.internal_static_eventlib_messages_DeviceInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo.class, com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo.Builder.class);
      }

      // Construct using com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        asset_ = "";

        category_ = "";

        control_ = "";

        function_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        os_ = "";

        osVersion_ = "";

        ownership_ = "";

        type_ = "";

        mfg_ = "";

        username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        totalRisk_ = 0F;

        if (firstseenBuilder_ == null) {
          firstseen_ = null;
        } else {
          firstseen_ = null;
          firstseenBuilder_ = null;
        }
        if (lastseenBuilder_ == null) {
          lastseen_ = null;
        } else {
          lastseen_ = null;
          lastseenBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.internal_static_eventlib_messages_DeviceInfo_descriptor;
      }

      @java.lang.Override
      public com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo getDefaultInstanceForType() {
        return com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo build() {
        com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo buildPartial() {
        com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo result = new com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo(this);
        int from_bitField0_ = bitField0_;
        result.deviceId_ = deviceId_;
        result.asset_ = asset_;
        result.category_ = category_;
        result.control_ = control_;
        if (((bitField0_ & 0x00000001) != 0)) {
          function_ = function_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.function_ = function_;
        result.os_ = os_;
        result.osVersion_ = osVersion_;
        result.ownership_ = ownership_;
        result.type_ = type_;
        result.mfg_ = mfg_;
        if (((bitField0_ & 0x00000002) != 0)) {
          username_ = username_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.username_ = username_;
        result.totalRisk_ = totalRisk_;
        if (firstseenBuilder_ == null) {
          result.firstseen_ = firstseen_;
        } else {
          result.firstseen_ = firstseenBuilder_.build();
        }
        if (lastseenBuilder_ == null) {
          result.lastseen_ = lastseen_;
        } else {
          result.lastseen_ = lastseenBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo) {
          return mergeFrom((com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo other) {
        if (other == com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getAsset().isEmpty()) {
          asset_ = other.asset_;
          onChanged();
        }
        if (!other.getCategory().isEmpty()) {
          category_ = other.category_;
          onChanged();
        }
        if (!other.getControl().isEmpty()) {
          control_ = other.control_;
          onChanged();
        }
        if (!other.function_.isEmpty()) {
          if (function_.isEmpty()) {
            function_ = other.function_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFunctionIsMutable();
            function_.addAll(other.function_);
          }
          onChanged();
        }
        if (!other.getOs().isEmpty()) {
          os_ = other.os_;
          onChanged();
        }
        if (!other.getOsVersion().isEmpty()) {
          osVersion_ = other.osVersion_;
          onChanged();
        }
        if (!other.getOwnership().isEmpty()) {
          ownership_ = other.ownership_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getMfg().isEmpty()) {
          mfg_ = other.mfg_;
          onChanged();
        }
        if (!other.username_.isEmpty()) {
          if (username_.isEmpty()) {
            username_ = other.username_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUsernameIsMutable();
            username_.addAll(other.username_);
          }
          onChanged();
        }
        if (other.getTotalRisk() != 0F) {
          setTotalRisk(other.getTotalRisk());
        }
        if (other.hasFirstseen()) {
          mergeFirstseen(other.getFirstseen());
        }
        if (other.hasLastseen()) {
          mergeLastseen(other.getLastseen());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object deviceId_ = "";
      /**
       * <code>string device_id = 1;</code>
       * @return The deviceId.
       */
      public java.lang.String getDeviceId() {
        java.lang.Object ref = deviceId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_id = 1;</code>
       * @return The bytes for deviceId.
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        java.lang.Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_id = 1;</code>
       * @param value The deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string device_id = 1;</code>
       * @param value The bytes for deviceId to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object asset_ = "";
      /**
       * <code>string asset = 2;</code>
       * @return The asset.
       */
      public java.lang.String getAsset() {
        java.lang.Object ref = asset_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          asset_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string asset = 2;</code>
       * @return The bytes for asset.
       */
      public com.google.protobuf.ByteString
          getAssetBytes() {
        java.lang.Object ref = asset_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          asset_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string asset = 2;</code>
       * @param value The asset to set.
       * @return This builder for chaining.
       */
      public Builder setAsset(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        asset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string asset = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAsset() {
        
        asset_ = getDefaultInstance().getAsset();
        onChanged();
        return this;
      }
      /**
       * <code>string asset = 2;</code>
       * @param value The bytes for asset to set.
       * @return This builder for chaining.
       */
      public Builder setAssetBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        asset_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object category_ = "";
      /**
       * <code>string category = 3;</code>
       * @return The category.
       */
      public java.lang.String getCategory() {
        java.lang.Object ref = category_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          category_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string category = 3;</code>
       * @return The bytes for category.
       */
      public com.google.protobuf.ByteString
          getCategoryBytes() {
        java.lang.Object ref = category_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          category_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string category = 3;</code>
       * @param value The category to set.
       * @return This builder for chaining.
       */
      public Builder setCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        category_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string category = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategory() {
        
        category_ = getDefaultInstance().getCategory();
        onChanged();
        return this;
      }
      /**
       * <code>string category = 3;</code>
       * @param value The bytes for category to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        category_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object control_ = "";
      /**
       * <code>string control = 4;</code>
       * @return The control.
       */
      public java.lang.String getControl() {
        java.lang.Object ref = control_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          control_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string control = 4;</code>
       * @return The bytes for control.
       */
      public com.google.protobuf.ByteString
          getControlBytes() {
        java.lang.Object ref = control_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          control_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string control = 4;</code>
       * @param value The control to set.
       * @return This builder for chaining.
       */
      public Builder setControl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        control_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string control = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearControl() {
        
        control_ = getDefaultInstance().getControl();
        onChanged();
        return this;
      }
      /**
       * <code>string control = 4;</code>
       * @param value The bytes for control to set.
       * @return This builder for chaining.
       */
      public Builder setControlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        control_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList function_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFunctionIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          function_ = new com.google.protobuf.LazyStringArrayList(function_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string function = 5;</code>
       * @return A list containing the function.
       */
      public com.google.protobuf.ProtocolStringList
          getFunctionList() {
        return function_.getUnmodifiableView();
      }
      /**
       * <code>repeated string function = 5;</code>
       * @return The count of function.
       */
      public int getFunctionCount() {
        return function_.size();
      }
      /**
       * <code>repeated string function = 5;</code>
       * @param index The index of the element to return.
       * @return The function at the given index.
       */
      public java.lang.String getFunction(int index) {
        return function_.get(index);
      }
      /**
       * <code>repeated string function = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the function at the given index.
       */
      public com.google.protobuf.ByteString
          getFunctionBytes(int index) {
        return function_.getByteString(index);
      }
      /**
       * <code>repeated string function = 5;</code>
       * @param index The index to set the value at.
       * @param value The function to set.
       * @return This builder for chaining.
       */
      public Builder setFunction(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFunctionIsMutable();
        function_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string function = 5;</code>
       * @param value The function to add.
       * @return This builder for chaining.
       */
      public Builder addFunction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFunctionIsMutable();
        function_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string function = 5;</code>
       * @param values The function to add.
       * @return This builder for chaining.
       */
      public Builder addAllFunction(
          java.lang.Iterable<java.lang.String> values) {
        ensureFunctionIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, function_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string function = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearFunction() {
        function_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string function = 5;</code>
       * @param value The bytes of the function to add.
       * @return This builder for chaining.
       */
      public Builder addFunctionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureFunctionIsMutable();
        function_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object os_ = "";
      /**
       * <code>string os = 6;</code>
       * @return The os.
       */
      public java.lang.String getOs() {
        java.lang.Object ref = os_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          os_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string os = 6;</code>
       * @return The bytes for os.
       */
      public com.google.protobuf.ByteString
          getOsBytes() {
        java.lang.Object ref = os_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          os_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string os = 6;</code>
       * @param value The os to set.
       * @return This builder for chaining.
       */
      public Builder setOs(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        os_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string os = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearOs() {
        
        os_ = getDefaultInstance().getOs();
        onChanged();
        return this;
      }
      /**
       * <code>string os = 6;</code>
       * @param value The bytes for os to set.
       * @return This builder for chaining.
       */
      public Builder setOsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        os_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object osVersion_ = "";
      /**
       * <code>string os_version = 7;</code>
       * @return The osVersion.
       */
      public java.lang.String getOsVersion() {
        java.lang.Object ref = osVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          osVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string os_version = 7;</code>
       * @return The bytes for osVersion.
       */
      public com.google.protobuf.ByteString
          getOsVersionBytes() {
        java.lang.Object ref = osVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          osVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string os_version = 7;</code>
       * @param value The osVersion to set.
       * @return This builder for chaining.
       */
      public Builder setOsVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        osVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string os_version = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearOsVersion() {
        
        osVersion_ = getDefaultInstance().getOsVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string os_version = 7;</code>
       * @param value The bytes for osVersion to set.
       * @return This builder for chaining.
       */
      public Builder setOsVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        osVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ownership_ = "";
      /**
       * <code>string ownership = 8;</code>
       * @return The ownership.
       */
      public java.lang.String getOwnership() {
        java.lang.Object ref = ownership_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ownership_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ownership = 8;</code>
       * @return The bytes for ownership.
       */
      public com.google.protobuf.ByteString
          getOwnershipBytes() {
        java.lang.Object ref = ownership_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ownership_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ownership = 8;</code>
       * @param value The ownership to set.
       * @return This builder for chaining.
       */
      public Builder setOwnership(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ownership_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ownership = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearOwnership() {
        
        ownership_ = getDefaultInstance().getOwnership();
        onChanged();
        return this;
      }
      /**
       * <code>string ownership = 8;</code>
       * @param value The bytes for ownership to set.
       * @return This builder for chaining.
       */
      public Builder setOwnershipBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ownership_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 9;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 9;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 9;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 9;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mfg_ = "";
      /**
       * <code>string mfg = 10;</code>
       * @return The mfg.
       */
      public java.lang.String getMfg() {
        java.lang.Object ref = mfg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mfg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mfg = 10;</code>
       * @return The bytes for mfg.
       */
      public com.google.protobuf.ByteString
          getMfgBytes() {
        java.lang.Object ref = mfg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mfg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mfg = 10;</code>
       * @param value The mfg to set.
       * @return This builder for chaining.
       */
      public Builder setMfg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mfg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mfg = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearMfg() {
        
        mfg_ = getDefaultInstance().getMfg();
        onChanged();
        return this;
      }
      /**
       * <code>string mfg = 10;</code>
       * @param value The bytes for mfg to set.
       * @return This builder for chaining.
       */
      public Builder setMfgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mfg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUsernameIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          username_ = new com.google.protobuf.LazyStringArrayList(username_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string username = 11;</code>
       * @return A list containing the username.
       */
      public com.google.protobuf.ProtocolStringList
          getUsernameList() {
        return username_.getUnmodifiableView();
      }
      /**
       * <code>repeated string username = 11;</code>
       * @return The count of username.
       */
      public int getUsernameCount() {
        return username_.size();
      }
      /**
       * <code>repeated string username = 11;</code>
       * @param index The index of the element to return.
       * @return The username at the given index.
       */
      public java.lang.String getUsername(int index) {
        return username_.get(index);
      }
      /**
       * <code>repeated string username = 11;</code>
       * @param index The index of the value to return.
       * @return The bytes of the username at the given index.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes(int index) {
        return username_.getByteString(index);
      }
      /**
       * <code>repeated string username = 11;</code>
       * @param index The index to set the value at.
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernameIsMutable();
        username_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string username = 11;</code>
       * @param value The username to add.
       * @return This builder for chaining.
       */
      public Builder addUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUsernameIsMutable();
        username_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string username = 11;</code>
       * @param values The username to add.
       * @return This builder for chaining.
       */
      public Builder addAllUsername(
          java.lang.Iterable<java.lang.String> values) {
        ensureUsernameIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, username_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string username = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string username = 11;</code>
       * @param value The bytes of the username to add.
       * @return This builder for chaining.
       */
      public Builder addUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureUsernameIsMutable();
        username_.add(value);
        onChanged();
        return this;
      }

      private float totalRisk_ ;
      /**
       * <code>float total_risk = 12;</code>
       * @return The totalRisk.
       */
      @java.lang.Override
      public float getTotalRisk() {
        return totalRisk_;
      }
      /**
       * <code>float total_risk = 12;</code>
       * @param value The totalRisk to set.
       * @return This builder for chaining.
       */
      public Builder setTotalRisk(float value) {
        
        totalRisk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float total_risk = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearTotalRisk() {
        
        totalRisk_ = 0F;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp firstseen_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> firstseenBuilder_;
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       * @return Whether the firstseen field is set.
       */
      public boolean hasFirstseen() {
        return firstseenBuilder_ != null || firstseen_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       * @return The firstseen.
       */
      public com.google.protobuf.Timestamp getFirstseen() {
        if (firstseenBuilder_ == null) {
          return firstseen_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : firstseen_;
        } else {
          return firstseenBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       */
      public Builder setFirstseen(com.google.protobuf.Timestamp value) {
        if (firstseenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          firstseen_ = value;
          onChanged();
        } else {
          firstseenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       */
      public Builder setFirstseen(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (firstseenBuilder_ == null) {
          firstseen_ = builderForValue.build();
          onChanged();
        } else {
          firstseenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       */
      public Builder mergeFirstseen(com.google.protobuf.Timestamp value) {
        if (firstseenBuilder_ == null) {
          if (firstseen_ != null) {
            firstseen_ =
              com.google.protobuf.Timestamp.newBuilder(firstseen_).mergeFrom(value).buildPartial();
          } else {
            firstseen_ = value;
          }
          onChanged();
        } else {
          firstseenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       */
      public Builder clearFirstseen() {
        if (firstseenBuilder_ == null) {
          firstseen_ = null;
          onChanged();
        } else {
          firstseen_ = null;
          firstseenBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       */
      public com.google.protobuf.Timestamp.Builder getFirstseenBuilder() {
        
        onChanged();
        return getFirstseenFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getFirstseenOrBuilder() {
        if (firstseenBuilder_ != null) {
          return firstseenBuilder_.getMessageOrBuilder();
        } else {
          return firstseen_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : firstseen_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp firstseen = 13;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getFirstseenFieldBuilder() {
        if (firstseenBuilder_ == null) {
          firstseenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getFirstseen(),
                  getParentForChildren(),
                  isClean());
          firstseen_ = null;
        }
        return firstseenBuilder_;
      }

      private com.google.protobuf.Timestamp lastseen_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> lastseenBuilder_;
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       * @return Whether the lastseen field is set.
       */
      public boolean hasLastseen() {
        return lastseenBuilder_ != null || lastseen_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       * @return The lastseen.
       */
      public com.google.protobuf.Timestamp getLastseen() {
        if (lastseenBuilder_ == null) {
          return lastseen_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : lastseen_;
        } else {
          return lastseenBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       */
      public Builder setLastseen(com.google.protobuf.Timestamp value) {
        if (lastseenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          lastseen_ = value;
          onChanged();
        } else {
          lastseenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       */
      public Builder setLastseen(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (lastseenBuilder_ == null) {
          lastseen_ = builderForValue.build();
          onChanged();
        } else {
          lastseenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       */
      public Builder mergeLastseen(com.google.protobuf.Timestamp value) {
        if (lastseenBuilder_ == null) {
          if (lastseen_ != null) {
            lastseen_ =
              com.google.protobuf.Timestamp.newBuilder(lastseen_).mergeFrom(value).buildPartial();
          } else {
            lastseen_ = value;
          }
          onChanged();
        } else {
          lastseenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       */
      public Builder clearLastseen() {
        if (lastseenBuilder_ == null) {
          lastseen_ = null;
          onChanged();
        } else {
          lastseen_ = null;
          lastseenBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       */
      public com.google.protobuf.Timestamp.Builder getLastseenBuilder() {
        
        onChanged();
        return getLastseenFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getLastseenOrBuilder() {
        if (lastseenBuilder_ != null) {
          return lastseenBuilder_.getMessageOrBuilder();
        } else {
          return lastseen_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : lastseen_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp lastseen = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getLastseenFieldBuilder() {
        if (lastseenBuilder_ == null) {
          lastseenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getLastseen(),
                  getParentForChildren(),
                  isClean());
          lastseen_ = null;
        }
        return lastseenBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:eventlib.messages.DeviceInfo)
    }

    // @@protoc_insertion_point(class_scope:eventlib.messages.DeviceInfo)
    private static final com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo();
    }

    public static com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceInfo>
        PARSER = new com.google.protobuf.AbstractParser<DeviceInfo>() {
      @java.lang.Override
      public DeviceInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.akhiltest.analytics.proto.model.messages.DeviceInfoMsg.DeviceInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventlib_messages_DeviceInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventlib_messages_DeviceInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#eventlib/messages/device_info.proto\022\021e" +
      "ventlib.messages\032\037google/protobuf/timest" +
      "amp.proto\"\264\002\n\nDeviceInfo\022\021\n\tdevice_id\030\001 " +
      "\001(\t\022\r\n\005asset\030\002 \001(\t\022\020\n\010category\030\003 \001(\t\022\017\n\007" +
      "control\030\004 \001(\t\022\020\n\010function\030\005 \003(\t\022\n\n\002os\030\006 " +
      "\001(\t\022\022\n\nos_version\030\007 \001(\t\022\021\n\townership\030\010 \001" +
      "(\t\022\014\n\004type\030\t \001(\t\022\013\n\003mfg\030\n \001(\t\022\020\n\010usernam" +
      "e\030\013 \003(\t\022\022\n\ntotal_risk\030\014 \001(\002\022-\n\tfirstseen" +
      "\030\r \001(\0132\032.google.protobuf.Timestamp\022,\n\010la" +
      "stseen\030\016 \001(\0132\032.google.protobuf.Timestamp" +
      "B=\n,com.akhiltest.analytics.proto.model." +
      "messagesB\rDeviceInfoMsgb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_eventlib_messages_DeviceInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eventlib_messages_DeviceInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventlib_messages_DeviceInfo_descriptor,
        new java.lang.String[] { "DeviceId", "Asset", "Category", "Control", "Function", "Os", "OsVersion", "Ownership", "Type", "Mfg", "Username", "TotalRisk", "Firstseen", "Lastseen", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
