// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventlib/messages/devices.proto

package com.akhiltest.analytics.proto.model.messages;

public final class DeviceAddEvent {
  private DeviceAddEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DeviceAddedOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eventlib.messages.DeviceAdded)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cust_id = 1;</code>
     * @return The custId.
     */
    java.lang.String getCustId();
    /**
     * <code>string cust_id = 1;</code>
     * @return The bytes for custId.
     */
    com.google.protobuf.ByteString
        getCustIdBytes();

    /**
     * <pre>
     *Represents from where the event is triggered
     * </pre>
     *
     * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
     * @return The enum numeric value on the wire for originType.
     */
    int getOriginTypeValue();
    /**
     * <pre>
     *Represents from where the event is triggered
     * </pre>
     *
     * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
     * @return The originType.
     */
    com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType getOriginType();

    /**
     * <code>string identifier = 3;</code>
     * @return The identifier.
     */
    java.lang.String getIdentifier();
    /**
     * <code>string identifier = 3;</code>
     * @return The bytes for identifier.
     */
    com.google.protobuf.ByteString
        getIdentifierBytes();

    /**
     * <code>string address = 4;</code>
     * @return The address.
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 4;</code>
     * @return The bytes for address.
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>string ip = 5;</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 5;</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>sint32 port = 6;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code eventlib.messages.DeviceAdded}
   */
  public static final class DeviceAdded extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:eventlib.messages.DeviceAdded)
      DeviceAddedOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeviceAdded.newBuilder() to construct.
    private DeviceAdded(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeviceAdded() {
      custId_ = "";
      originType_ = 0;
      identifier_ = "";
      address_ = "";
      ip_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeviceAdded();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceAdded(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              custId_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              originType_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              identifier_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 48: {

              port_ = input.readSInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.internal_static_eventlib_messages_DeviceAdded_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.internal_static_eventlib_messages_DeviceAdded_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.class, com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.Builder.class);
    }

    /**
     * Protobuf enum {@code eventlib.messages.DeviceAdded.OriginType}
     */
    public enum OriginType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>BLE_SNIFF = 100;</code>
       */
      BLE_SNIFF(100),
      /**
       * <code>BT_SNIFF = 200;</code>
       */
      BT_SNIFF(200),
      /**
       * <code>WIFI_SNIFF = 300;</code>
       */
      WIFI_SNIFF(300),
      /**
       * <code>MED_SNIFF = 400;</code>
       */
      MED_SNIFF(400),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>BLE_SNIFF = 100;</code>
       */
      public static final int BLE_SNIFF_VALUE = 100;
      /**
       * <code>BT_SNIFF = 200;</code>
       */
      public static final int BT_SNIFF_VALUE = 200;
      /**
       * <code>WIFI_SNIFF = 300;</code>
       */
      public static final int WIFI_SNIFF_VALUE = 300;
      /**
       * <code>MED_SNIFF = 400;</code>
       */
      public static final int MED_SNIFF_VALUE = 400;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static OriginType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static OriginType forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 100: return BLE_SNIFF;
          case 200: return BT_SNIFF;
          case 300: return WIFI_SNIFF;
          case 400: return MED_SNIFF;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<OriginType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          OriginType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<OriginType>() {
              public OriginType findValueByNumber(int number) {
                return OriginType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.getDescriptor().getEnumTypes().get(0);
      }

      private static final OriginType[] VALUES = values();

      public static OriginType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private OriginType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:eventlib.messages.DeviceAdded.OriginType)
    }

    public static final int CUST_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object custId_;
    /**
     * <code>string cust_id = 1;</code>
     * @return The custId.
     */
    @java.lang.Override
    public java.lang.String getCustId() {
      java.lang.Object ref = custId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        custId_ = s;
        return s;
      }
    }
    /**
     * <code>string cust_id = 1;</code>
     * @return The bytes for custId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustIdBytes() {
      java.lang.Object ref = custId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        custId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORIGIN_TYPE_FIELD_NUMBER = 2;
    private int originType_;
    /**
     * <pre>
     *Represents from where the event is triggered
     * </pre>
     *
     * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
     * @return The enum numeric value on the wire for originType.
     */
    @java.lang.Override public int getOriginTypeValue() {
      return originType_;
    }
    /**
     * <pre>
     *Represents from where the event is triggered
     * </pre>
     *
     * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
     * @return The originType.
     */
    @java.lang.Override public com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType getOriginType() {
      @SuppressWarnings("deprecation")
      com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType result = com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType.valueOf(originType_);
      return result == null ? com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType.UNRECOGNIZED : result;
    }

    public static final int IDENTIFIER_FIELD_NUMBER = 3;
    private volatile java.lang.Object identifier_;
    /**
     * <code>string identifier = 3;</code>
     * @return The identifier.
     */
    @java.lang.Override
    public java.lang.String getIdentifier() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        identifier_ = s;
        return s;
      }
    }
    /**
     * <code>string identifier = 3;</code>
     * @return The bytes for identifier.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdentifierBytes() {
      java.lang.Object ref = identifier_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        identifier_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 4;</code>
     * @return The address.
     */
    @java.lang.Override
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 4;</code>
     * @return The bytes for address.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 5;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 5;</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 5;</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 6;
    private int port_;
    /**
     * <code>sint32 port = 6;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCustIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, custId_);
      }
      if (originType_ != com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType.UNKNOWN.getNumber()) {
        output.writeEnum(2, originType_);
      }
      if (!getIdentifierBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, identifier_);
      }
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, address_);
      }
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, ip_);
      }
      if (port_ != 0) {
        output.writeSInt32(6, port_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCustIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, custId_);
      }
      if (originType_ != com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, originType_);
      }
      if (!getIdentifierBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, identifier_);
      }
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, address_);
      }
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt32Size(6, port_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded)) {
        return super.equals(obj);
      }
      com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded other = (com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded) obj;

      if (!getCustId()
          .equals(other.getCustId())) return false;
      if (originType_ != other.originType_) return false;
      if (!getIdentifier()
          .equals(other.getIdentifier())) return false;
      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CUST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCustId().hashCode();
      hash = (37 * hash) + ORIGIN_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + originType_;
      hash = (37 * hash) + IDENTIFIER_FIELD_NUMBER;
      hash = (53 * hash) + getIdentifier().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eventlib.messages.DeviceAdded}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eventlib.messages.DeviceAdded)
        com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAddedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.internal_static_eventlib_messages_DeviceAdded_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.internal_static_eventlib_messages_DeviceAdded_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.class, com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.Builder.class);
      }

      // Construct using com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        custId_ = "";

        originType_ = 0;

        identifier_ = "";

        address_ = "";

        ip_ = "";

        port_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.internal_static_eventlib_messages_DeviceAdded_descriptor;
      }

      @java.lang.Override
      public com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded getDefaultInstanceForType() {
        return com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.getDefaultInstance();
      }

      @java.lang.Override
      public com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded build() {
        com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded buildPartial() {
        com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded result = new com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded(this);
        result.custId_ = custId_;
        result.originType_ = originType_;
        result.identifier_ = identifier_;
        result.address_ = address_;
        result.ip_ = ip_;
        result.port_ = port_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded) {
          return mergeFrom((com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded other) {
        if (other == com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.getDefaultInstance()) return this;
        if (!other.getCustId().isEmpty()) {
          custId_ = other.custId_;
          onChanged();
        }
        if (other.originType_ != 0) {
          setOriginTypeValue(other.getOriginTypeValue());
        }
        if (!other.getIdentifier().isEmpty()) {
          identifier_ = other.identifier_;
          onChanged();
        }
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object custId_ = "";
      /**
       * <code>string cust_id = 1;</code>
       * @return The custId.
       */
      public java.lang.String getCustId() {
        java.lang.Object ref = custId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          custId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cust_id = 1;</code>
       * @return The bytes for custId.
       */
      public com.google.protobuf.ByteString
          getCustIdBytes() {
        java.lang.Object ref = custId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          custId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cust_id = 1;</code>
       * @param value The custId to set.
       * @return This builder for chaining.
       */
      public Builder setCustId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        custId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cust_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustId() {
        
        custId_ = getDefaultInstance().getCustId();
        onChanged();
        return this;
      }
      /**
       * <code>string cust_id = 1;</code>
       * @param value The bytes for custId to set.
       * @return This builder for chaining.
       */
      public Builder setCustIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        custId_ = value;
        onChanged();
        return this;
      }

      private int originType_ = 0;
      /**
       * <pre>
       *Represents from where the event is triggered
       * </pre>
       *
       * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
       * @return The enum numeric value on the wire for originType.
       */
      @java.lang.Override public int getOriginTypeValue() {
        return originType_;
      }
      /**
       * <pre>
       *Represents from where the event is triggered
       * </pre>
       *
       * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
       * @param value The enum numeric value on the wire for originType to set.
       * @return This builder for chaining.
       */
      public Builder setOriginTypeValue(int value) {
        
        originType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Represents from where the event is triggered
       * </pre>
       *
       * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
       * @return The originType.
       */
      @java.lang.Override
      public com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType getOriginType() {
        @SuppressWarnings("deprecation")
        com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType result = com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType.valueOf(originType_);
        return result == null ? com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *Represents from where the event is triggered
       * </pre>
       *
       * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
       * @param value The originType to set.
       * @return This builder for chaining.
       */
      public Builder setOriginType(com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded.OriginType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        originType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Represents from where the event is triggered
       * </pre>
       *
       * <code>.eventlib.messages.DeviceAdded.OriginType origin_type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOriginType() {
        
        originType_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object identifier_ = "";
      /**
       * <code>string identifier = 3;</code>
       * @return The identifier.
       */
      public java.lang.String getIdentifier() {
        java.lang.Object ref = identifier_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          identifier_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string identifier = 3;</code>
       * @return The bytes for identifier.
       */
      public com.google.protobuf.ByteString
          getIdentifierBytes() {
        java.lang.Object ref = identifier_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          identifier_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string identifier = 3;</code>
       * @param value The identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifier(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        identifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string identifier = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdentifier() {
        
        identifier_ = getDefaultInstance().getIdentifier();
        onChanged();
        return this;
      }
      /**
       * <code>string identifier = 3;</code>
       * @param value The bytes for identifier to set.
       * @return This builder for chaining.
       */
      public Builder setIdentifierBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        identifier_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 4;</code>
       * @return The address.
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 4;</code>
       * @return The bytes for address.
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 4;</code>
       * @param value The address to set.
       * @return This builder for chaining.
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 4;</code>
       * @param value The bytes for address to set.
       * @return This builder for chaining.
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 5;</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 5;</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 5;</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 5;</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>sint32 port = 6;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>sint32 port = 6;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>sint32 port = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:eventlib.messages.DeviceAdded)
    }

    // @@protoc_insertion_point(class_scope:eventlib.messages.DeviceAdded)
    private static final com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded();
    }

    public static com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceAdded>
        PARSER = new com.google.protobuf.AbstractParser<DeviceAdded>() {
      @java.lang.Override
      public DeviceAdded parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceAdded(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeviceAdded> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceAdded> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.akhiltest.analytics.proto.model.messages.DeviceAddEvent.DeviceAdded getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventlib_messages_DeviceAdded_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventlib_messages_DeviceAdded_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037eventlib/messages/devices.proto\022\021event" +
      "lib.messages\"\367\001\n\013DeviceAdded\022\017\n\007cust_id\030" +
      "\001 \001(\t\022>\n\013origin_type\030\002 \001(\0162).eventlib.me" +
      "ssages.DeviceAdded.OriginType\022\022\n\nidentif" +
      "ier\030\003 \001(\t\022\017\n\007address\030\004 \001(\t\022\n\n\002ip\030\005 \001(\t\022\014" +
      "\n\004port\030\006 \001(\021\"X\n\nOriginType\022\013\n\007UNKNOWN\020\000\022" +
      "\r\n\tBLE_SNIFF\020d\022\r\n\010BT_SNIFF\020\310\001\022\017\n\nWIFI_SN" +
      "IFF\020\254\002\022\016\n\tMED_SNIFF\020\220\003B>\n,com.akhiltest." +
      "analytics.proto.model.messagesB\016DeviceAd" +
      "dEventb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_eventlib_messages_DeviceAdded_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eventlib_messages_DeviceAdded_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventlib_messages_DeviceAdded_descriptor,
        new java.lang.String[] { "CustId", "OriginType", "Identifier", "Address", "Ip", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
